name: 'dbt_dengue'
version: '1.0.0'
config-version: 2

profile: 'dbt_dengue'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_dengue:
    staging:
      +materialized: view
      +schema: staging
    
    marts:
      +materialized: table
      +schema: gold
      +tags: ["gold", "bi_ready"]
